name: Validate Bicep

on:
  push:
    paths:
      - "infrastructure/**"
      - ".github/workflows/bicep-validate.yml"
  pull_request:
    paths:
      - "infrastructure/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Bicep
        uses: azure/cli@v2
        with:
          inlineScript: az bicep build --file infrastructure/main.bicep
